http.port : "8081"
https:
  port: "8082"
  path: "/api/v1/*"
  certs:
    alias: "mule"
    password: "......"
    path: "certs/ba-card-papi-keystore.jks"
    

experianSapi:
  host: "ba-experian-sapi.us-e2.cloudhub.io"
  port: "8082"
  api: "/api/v1"
  creditscore: "creditscore"

convertAPI:
  host: "v2.convertapi.com"
  secret: "....."
  path: "/convert/htm/to/pdf"
  
docusign.emailId: "remya.r@njclabs.com,joji.varghese@njclabs.com,vishnupriya.ph@njclabs.com"  

docusignSapi:
  #host: "wma-docusign-sapi.us-e2.cloudhub.io"
  host: "ba-docusign-sapi.us-e2.cloudhub.io" 
  protocol: "HTTPS"
  basePath: "/api/v1"
  postDocumentPath: "/documents"
  clientId: "...."
  clientSecret: "....."    
  
notificationSapi:
  host: "ba-notification-sapi.us-e2.cloudhub.io" 
  api: "/api/v1"
  createNotification: "/creditcardnotification"
  
foreach.batchSize: "1"


  
transaction.mode: "CreditCard"  

creditCardStatus: "Active"
newCreditCardRequested : "yes"
deactivateCreditCard : "yes"
oldCreditCardStatus: "De-activate"


tracePoint:
  request: "REQUEST_RECEIVED"
  response: "RESPONSE_RETURNED"
  entry: "FLOW_ENTRY"
  complete: "FLOW_COMPLETE"
  info: "PROCESS_INFO"
  before.outbound: "BEFORE_OUTBOUND"
  after.outbound: "AFTER_OUTBOUND"
  before.transform: "BEFORE_TRANSFORM_MESSAGE" 
  after.transform: "AFTER_TRANSFORM_MESSAGE"
  error: "ERROR"
priority:
  info: "INFO"
  debug: "DEBUG"
  error: "ERROR"
env: "dev"